In [18]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
# Scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [3]:
scalar.ndim

0

In [4]:
# Get Item Back
scalar.item()

7

In [5]:
#Vector
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [6]:
vector.ndim

1

In [7]:
vector.shape

torch.Size([2])

In [8]:
# MATRIX
MATRIX = torch.tensor([[7, 8],
                       [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [9]:
MATRIX.ndim

2

In [10]:
MATRIX[0]

tensor([7, 8])

In [11]:
MATRIX[1]

tensor([ 9, 10])

In [12]:
MATRIX.shape

torch.Size([2, 2])

In [13]:
# TENSOR
TENSOR = torch.tensor([[[1, 2, 3],
                        [3, 6, 9],
                        [2, 4, 5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [14]:
TENSOR.ndim

3

In [15]:
TENSOR.shape

torch.Size([1, 3, 3])

In [16]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

In [17]:
# Create a random tensor of size (3, 4)
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.7152, 0.3806, 0.6781, 0.7759],
        [0.4174, 0.7548, 0.6936, 0.2582],
        [0.1029, 0.3388, 0.4259, 0.4816]])

In [18]:
# Create a random tensor with similar size to image tensor
rand_image_size = torch.rand(size=(224,224,3)) # height, width, color channels (rgb)
rand_image_size.shape, rand_image_size.ndim

(torch.Size([224, 224, 3]), 3)

In [19]:
# Create a tensor of all zeros
zeros = torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [20]:
# Create a tensor of all ones
ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [21]:
ones.dtype

torch.float32

In [22]:
# Use torch.arange()
arange = torch.arange(start=1, end=11, step=1)
arange

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [23]:
# Creating tensors like

In [24]:
ten_zeros = torch.zeros_like(input=arange)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [25]:
exTensor = torch.tensor([3.0, 6.0, 9.0],
                        dtype=None, # Data Type
                        device=None, # Device it's running on "cpu", "gpu", etc
                        requires_grad=False) # Whether or not to track gradients
exTensor

tensor([3., 6., 9.])

In [26]:
exTensor.dtype

torch.float32

In [27]:
f16tensor = exTensor.type(torch.float16)
f16tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [28]:
exTensor.device

device(type='cpu')

In [29]:
tensor = torch.tensor([1, 2, 3])
tensor + 10

tensor([11, 12, 13])

In [30]:
# Element wise multiplication
torch.matmul(tensor, tensor)

tensor(14)

In [31]:
tensor1 = torch.tensor([[1, 2],
                       [3, 4],
                       [5, 6]])
tensor2 = torch.tensor([[7, 10],
                       [8, 11],
                       [9, 12]])

#Error: tensor.mm(tensor1, tensor2) # same as matmul just less chars

torch.mm(tensor1, tensor2.T)

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

In [32]:
# Min, Max, Mean, Sum
x = torch.arange(0, 100, 10)
print(x.min())
print(x.max())
print(torch.mean(x.type(torch.float32))) # Requires float or complex
print(x.sum())

tensor(0)
tensor(90)
tensor(45.)
tensor(450)


In [34]:
# Find position
print(x.argmin())
print(x.argmax())

tensor(0)
tensor(9)


In [3]:
import torch
x = torch.arange (1., 10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [4]:
# Reshape (has to equal num of elements)
x_reshaped = x.reshape(1, 9)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [5]:
# Change view
z = x.view(1,9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [6]:
# Changing z changes x (shares same memory)
z[:, 0] = 5
z, x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [7]:
# Stack tensors on top of each other
x_stacked = torch.stack([x, x, x, x], dim=0)
x_stacked
# hstack and vstack also

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [8]:
#torch.squeeze() removes all single dimensions from a target tensor
x_reshaped

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [9]:
x_squeezed = x_reshaped.squeeze()
x_squeezed

tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])

In [10]:
# torch.unsqueeze() adds a dimension to tensor at a specific dim (dimension)
print(x_squeezed, x_squeezed.shape)

x_unsqueezed = x_squeezed.unsqueeze(dim=0)
print(x_unsqueezed, x_unsqueezed.shape)

tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]) torch.Size([9])
tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]) torch.Size([1, 9])


In [11]:
#torch.permute() rearranges the dimensions of a target tensor in a specified order
x_original = torch.rand(size=(224, 244, 3)) # height, width, color chnls

# permute original tensor to rearrange the axis (or dim) order
x_permuted = x_original.permute(2, 0 , 1) #shifts axis 0->1, 1->2, 2->0
print(x_original.shape, x_permuted.shape)

torch.Size([224, 244, 3]) torch.Size([3, 224, 244])


In [12]:
x_original[0, 0, 0] = 728218
x_original[0, 0, 0], x_permuted[0, 0, 0]

(tensor(728218.), tensor(728218.))

In [13]:
import torch
x = torch.arange(1, 10).reshape(1, 3, 3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [14]:
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [15]:
x[0][0] # dim 1

tensor([1, 2, 3])

In [16]:
x[0][0][0]

tensor(1)

In [17]:
#Use : to select all of target dimension
x[:, 0]

tensor([[1, 2, 3]])

In [18]:
# Get all values of 0th and 1st dim and index 1 or 2nd
x[:, :, 1]

tensor([[2, 5, 8]])

In [19]:
x[:, 1, 1]

tensor([5])

In [20]:
x[0, 0, :]

tensor([1, 2, 3])

In [1]:
#Numpy array to tensor
import torch
import numpy as np

array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array) # when converting pytorch reflects numpy's default datatype (float64) unless specified
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [2]:
# change value of array
array = array + 1
array, tensor

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [4]:
#Tensor to numpy array
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [7]:
#Change the tensor, doesn't change numpy
tensor = tensor + 1
tensor, numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [9]:
#reproducibility 
import torch

randTensor1 = torch.rand(3, 4)
randTensor2 = torch.rand(3, 4)

print(randTensor1, randTensor2, randTensor1 == randTensor2)

tensor([[6.3914e-04, 7.8566e-01, 8.1927e-01, 2.9395e-01],
        [9.3135e-01, 6.0171e-02, 3.6868e-02, 1.4815e-01],
        [9.9757e-01, 8.5508e-01, 1.9006e-01, 7.7246e-01]]) tensor([[0.4113, 0.8417, 0.8106, 0.3708],
        [0.5182, 0.3210, 0.9286, 0.2502],
        [0.7688, 0.5101, 0.6590, 0.6990]]) tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [11]:
# random but reproducible tensors
import torch

#Set seed
RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)

randTensor3 = torch.rand(3,4)
torch.manual_seed(RANDOM_SEED) #Required to reset otherwise it changes
randTensor4 = torch.rand(3,4)
print(randTensor3, randTensor4, randTensor3 == randTensor4)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]]) tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]]) tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


In [12]:
 !nvidia-smi

Mon Sep 26 14:16:11 2022       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 510.73.05    Driver Version: 510.73.05    CUDA Version: 11.6     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Quadro M4000        Off  | 00000000:00:05.0 Off |                  N/A |
| 46%   25C    P8    11W / 120W |      3MiB /  8192MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

In [20]:
import torch
torch.cuda.is_available()

True

In [21]:
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [22]:
torch.cuda.device_count()

1

In [23]:
tensor = torch.tensor([1, 2, 3])

print(tensor, tensor.device)

tensor([1, 2, 3]) cpu


In [24]:
tensorgpu = tensor.to(device)
tensorgpu

tensor([1, 2, 3], device='cuda:0')

In [25]:
#Can't transform with numpy on gpu
tensorcpu = tensorgpu.cpu().numpy()
tensorcpu

array([1, 2, 3])

In [26]:
#EXtra 
randTensor = torch.rand(7,7)
tensor2 = torch.rand(1,7)
matmul = torch.mm(randTensor, tensor2.T)